const HDLD_LUNCHBOX = "LCB";

//Commented out everything relating to carrying multiple boxes, because
//it causes a VM abort when dropping one. I don't think it's necessary to carry more than one anyway,
//so it's all good.		-Slogstin


enum LCHBXPouchSlots {

	// From HDStorageItemStats
	// ------------------------

	// SISTAT_ININDEX  = 1,
	// SISTAT_SELINDEX = 2,
	// SISTAT_HOWMANY  = 3,
	// SISTAT_SCROLL   = 4,

	// SI_WEPICONSLOT  = HDWEP_STATUSSLOTS + 1,
	// SI_WEPBULKSLOT  = HDWEP_STATUSSLOTS + 2,
	// SI_MAXROWS      = 10,
	// SI_MAXBUNCH     = 20,
	// SI_SCROLLCYCLE  = (2 << 9),

	LCHBX_AMOUNT       = 5
}
//==================================================
// Base Definition
//==================================================
class VIRLunchbox : HDStorageItem {

	default {
		+Inventory.INVBAR
		+Weapon.WIMPY_WEAPON
		+HDWeapon.FITSINBACKPACK

		Tag "$TAG_LUNCHBOX";
		Inventory.Icon "LCBXA0";
		Inventory.PickupMessage "$PICKUP_LUNCHBOX";
		Inventory.PickupSound "Lunchbox/Pick";
		scale 0.6;

		hdweapon.wornlayer 0;
		hdweapon.refid HDLD_LUNCHBOX;

		HDStorageItem.MinBulk 20;
		HDStorageItem.MaxCapacity 200;
		HDStorageItem.MaxBunch 10;
	}

	override bool IsBeingWorn() { return false; }

	override double WeaponBulk() {
		return ContainerBulk(itemBulk);
	}

	override double ContainerBulk(double it) const {
		return max(it * 0.4, minBulk);
	}

	override bool CanFitInThisContainer(Class<Inventory> itemType) {
		return HDCore.isChildClass(itemType, 'UaS_Consumable');
	}

	override bool ThisCanFitInThisContainer(Inventory item) {
		return HDCore.isChildClass(item.getClass(), 'UaS_Consumable');
	}

	override void actualpickup(actor other, bool silent) {
		let HeldLCHBX = VIRLunchbox(other.findinventory("VIRLunchbox"));
		if (HeldLCHBX) {
			/*
			HeldLCHBX.weaponStatus[LCHBX_AMOUNT]++;
			HeldLCHBX.maxCapacity = HeldLCHBX.weaponStatus[LCHBX_AMOUNT] * HeldLCHBX.default.maxCapacity;

			while (items.size()) {

				string itemCls, prefix;
				[itemCls, prefix] = itemClassAndPrefix(0);

				let amt = count(itemCls);
				gsp.insert(extract(0, amt), amt);
			}

			destroy();
			*/
			return;
		}
		super.actualpickup(other, silent);
	}

	States {
		Spawn:
			LCBX ABC -1 NoDelay
			{
				if (invoker.items.size() == 0)
				{
					frame = 1;
				}
				else if (target)
				{
					translation = target.translation;
					frame = 2;
				}

				invoker.bNO_AUTO_SWITCH = false;
			}
			Stop;
		Select0:
			TNT1 A 10 {
				A_StartSound("Lunchbox/open", CHAN_WEAPON);
				if (invoker.itemBulk > (1000 * 0.7)) A_SetTics(20);
			}
			Goto super::select0;
	}
}

class LCHBXStorageItemList : HDStorageItemList {
	override bool CanAdd(Class<Inventory> itemCls) {
		return HDCore.isChildClass(itemCls, 'UaS_Consumable');
	}
}

class WildLCHBX : IdleDummy {
	override void postbeginplay() {
		super.postbeginplay();

		let SpawnedLCHBX = VirLunchbox(spawn("VirLunchbox", pos, ALLOW_REPLACE));
		SpawnedLCHBX.RandomContents("LCHBXStorageItemList", frandom(0.1, 0.5), false);
		
		SpawnedLCHBX.vel = vel;
		HDF.TransferSpecials(self, SpawnedLCHBX);

		destroy();
	}
}
